### ISSUE TITLE
Unable to use underscore functions inside template?

### ISSUE THREAD

**Issue by kyllle** [emaphp/underscore-template-loader#10]
When I use this plugin and use an underscore function inside my template I get an error `Uncaught ReferenceError: _ is not defined` pointing to the `_.each()` being used in the template?

**Comment by SpaceK33z** [comment]
`_` needs to be globally available for this to work. Can you try to add the following to your webpack config?

```js
{
    plugins: [
        new webpack.ProvidePlugin({
            _: 'underscore'
        })
    ]
}
```

**Comment by kyllle** [comment]
That's it, thanks for this!! I had originally added plugins inside the modules object.

**Comment by arjunmayilvaganan** [comment]
@SpaceK33z
Not sure why we can't use `underscore` functions inside `underscore` templates.

If `underscore` is what renders the templates, then is it not what evaluates the expressions or statements inside the templates, such as `_.each()`?
