### ISSUE TITLE
Is this module still active?

### ISSUE THREAD

**Issue by jantimon** [emaphp/underscore-template-loader#11]
Hi,
is this module still maintained and used?

**Comment by SpaceK33z** [comment]
Yeah, we use it a lot at my work. I have contributed some code in the past and it was merged quickly. It has loads of tests and it's stable now :).

**Comment by jantimon** [comment]
It fails if no image loader is specified.
Could we instead use a underscore-template-loader-image-loader (with a bettername) which checks if any loader is present and if not just returns the filename?

Similar to: https://github.com/ampedandwired/html-webpack-plugin/blob/feature/loaders/lib/loader.js#L14-L17

**Comment by jantimon** [comment]
Added a fallback loader in #12

**Comment by emaphp** [comment]
Yes quite.
Truth is, it's summer here so I'm kind on 'vacations'..
I'm checking out all the issues you opened, thanks in advance for you collaboration.

**Comment by jantimon** [comment]
No worries - saw that the last commit was made 3 month ago so I just wanted to make sure that it is still maintained before looking into the code :)
