### ISSUE TITLE
Support for _.templateSettings.imports?

### ISSUE THREAD

**Issue by kmck** [emaphp/underscore-template-loader#15]
Any plans to add support for [_.templateSettings.imports](https://lodash.com/docs#templateSettings-imports)? I'm trying to convert a browserify-based workflow that relies on the feature to webpack, so currently I'd need to shim all the instances of the templates.

I can imagine it being slightly tricky to implement, but here's how [jstify](https://github.com/zertosh/jstify) does it, in case it's of any interest: https://github.com/zertosh/jstify/blob/master/index.js#L45

**Comment by emaphp** [comment]
Mmm, I guess we can use loaderUtils.urlToRequest to emulate the part that concatenates

```javascript
var engineRequire = 'var _ = require(\'' + engine + '\');\n';
```

at the beginning (maybe?) and then reproduce this line https://github.com/zertosh/jstify/blob/master/index.js#L53.

What I'm not sure is how are you going to define the values to import. Are you planning on defining them in the webpack.config.js? It's been months since I've touched js and I've already forgot webpack internals.

**Comment by kmck** [comment]
The way `jstify` does it, it will load from `_.templateSettings.imports` defined on the engine. I like that because it allows consistent behavior between imported templates and templates created using `_.template`, although I wouldn't be surprised if other people would want to configure it separately. 

A side-effect of this approach is that the `require` order of modules will determine whether the imports are available in a given template (ie. you need to make sure to add them to `_.templateSettings.imports` before you `require` the template, otherwise they won't be available), although the same thing happens using `_.template` directly, so...

I've been working on converting an existing Browserify-based project to Webpack, which is why I ran into this and wanted to open the issue, but I'm not very familiar with Webpack yet, so I'm not sure whether this goes against the spirit of its loaders.

**Comment by emaphp** [comment]
Sorry for not giving a response in all this time, I've been having medical issues. I'll reviewing these changes and hopefully update the repository asap. Thanks in advance for your contributions.

**Comment by kmck** [comment]
No worries. Hope everything is okay!
