### ISSUE TITLE
Register on bower

### ISSUE THREAD

**Issue by irishkurisu** [emaphp/underscore-template-loader#2]
It would be really useful to have this registered on bower, as well as npm.

http://bower.io/docs/creating-packages/

**Comment by emaphp** [comment]
is that even possible? i've never heard of webpack loaders installed through bower but i'll do my research. i'll let you know if i come up with something

**Comment by irishkurisu** [comment]
It is possible but not highly recommended by webpack, so I totally understand why you never did.  I have my hand a bit forced, though, because of some other packages that are only available on bower and we are exploring moving to either one or the other.

**Comment by emaphp** [comment]
I did my research and I couldn't find a way to run a loader reading from the bower_components dir. This might have to do with the way dependencies are managed in webpack (not a webpack expert tbh) .You can however load modules installed through bower.

**main.js**

```javascript
var $ = require('jquery');
var _ = require('underscore');
var tpl = require('../templates/hello_world.html');

$(function () {
    $('#content').html(tpl({message: 'Hello'}));
});
```

**webpack.config.js**

```javascript
var path = require("path");
var webpack = require("webpack");

module.exports = {
    entry: "./js/main.js",

    output: {
        path: __dirname,
        filename: "bundle.js"
    },

    node: {
        fs: "empty"
    },

    module: {
        loaders: [
            { test: /\.html/, loader: "underscore-template-loader" }
        ]
    },

    resolve: {
        root: [path.join(__dirname, "bower_components")]
    },

    plugins: [
        new webpack.ResolverPlugin(
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
        )
    ]
};
```
