### ISSUE TITLE
Requiring images

### ISSUE THREAD

**Issue by SpaceK33z** [emaphp/underscore-template-loader#3]
How would you require images in a template? `html-loader` doesn't work with this loader, so I think it's necessary to merge a bit of the `html-loader` logic in this loader for this to work.

See also altano/handlebars-loader#37

**Comment by emaphp** [comment]
this could be an interesting feature. I'm looking at html-loader source code right now. I'll let you know if I come up with something.

**Comment by emaphp** [comment]
I've added support for images through file-loader and url-loader. I just published these changes through npm and they're already available in 0.3.

**Comment by SpaceK33z** [comment]
Thanks! I will try it out next week, on vacation now ;).

**Comment by SpaceK33z** [comment]
Tested it, works perfectly. Thank you again :).
