### ISSUE TITLE
support for _.templateSettings.variable ?

### ISSUE THREAD

**Issue by pascalpp** [emaphp/underscore-template-loader#8]
In our codebase, we have `_.templateSettings.variable` set to `'data'`, so all our model data gets exposed into views as `data.foo` or `data.bar`. Is this setting supported by underscore-template-loader?

**Comment by pascalpp** [comment]
oh looks like it might be trivial to add. PR coming.

**Comment by SpaceK33z** [comment]
You should add a test for this.

**Comment by pascalpp** [comment]
Yeah i figured it should have a test. How do I run the tests in this repo?

**Comment by SpaceK33z** [comment]
`npm test` should run the tests ;).

**Comment by pascalpp** [comment]
sure enough : )
